vscode:
  extensions:
    - ms-python.python@2019.10.44104:fKYRb8X8FA37fMd+hgvv2A==
    - cstrap.flask-snippets@0.1.1:jTFLsRjui14Kjw/tcWpOiw==
    - VisualStudioExptTeam.vscodeintellicode@1.2.0:ZVy7XFOZUd4m0FZb3PUFbA==
    - magicstack.MagicPython@1.1.0:j4FYz9tfFt//ke3wUcL3VQ==